/**
 * Mapbox dialect scorer.
 *
 * Heuristic signals that indicate a style targets Mapbox GL JS or was
 * generated by Mapbox Studio.
 */

export function scoreMapbox(style: Record<string, unknown>): number {
  let score = 0;

  // --- Sources with mapbox:// URLs ---
  const sources = style.sources;
  if (typeof sources === "object" && sources !== null) {
    for (const src of Object.values(sources as Record<string, unknown>)) {
      if (typeof src === "object" && src !== null) {
        const url = (src as Record<string, unknown>).url;
        if (typeof url === "string" && url.startsWith("mapbox://")) {
          score += 10;
          break;
        }
      }
    }
  }

  // --- Sprite starts with mapbox:// ---
  if (typeof style.sprite === "string" && style.sprite.startsWith("mapbox://")) {
    score += 10;
  }

  // --- Glyphs starts with mapbox:// ---
  if (typeof style.glyphs === "string" && style.glyphs.startsWith("mapbox://")) {
    score += 10;
  }

  // --- Proprietary top-level properties ---
  if (style.fog !== undefined) score += 5;
  if (style.imports !== undefined) score += 5;
  if (style.schema !== undefined) score += 5;
  if (Array.isArray(style.lights)) score += 5;

  // --- Metadata with mapbox: prefixed keys ---
  const metadata = style.metadata;
  if (typeof metadata === "object" && metadata !== null) {
    for (const key of Object.keys(metadata as Record<string, unknown>)) {
      if (key.startsWith("mapbox:")) {
        score += 3;
        break;
      }
    }
  }

  // --- Studio-specific top-level fields ---
  if (style.owner !== undefined || style.visibility !== undefined || style.draft !== undefined) {
    score += 3;
  }

  // --- Mapbox-specific layer types ---
  const mapboxTypes = new Set(["building", "model", "slot", "clip"]);
  const layers = style.layers;
  if (Array.isArray(layers)) {
    for (const layer of layers as Array<Record<string, unknown>>) {
      if (typeof layer === "object" && layer !== null && mapboxTypes.has(layer.type as string)) {
        score += 5;
        break;
      }
    }
  }

  // --- Mapbox-specific top-level weather / camera / theme ---
  if (
    style.snow !== undefined ||
    style.rain !== undefined ||
    style.camera !== undefined ||
    (style as Record<string, unknown>)["color-theme"] !== undefined
  ) {
    score += 5;
  }

  return score;
}
